sudo: false
language: python
python:
    # We don't actually use the Travis Python, but this keeps it organized.
    - "2.7"
    - "3.4"

addons:
    apt:
        packages:
            - libatlas-dev
            - libatlas-base-dev
            - liblapack-dev
            - gfortran
            - libhdf5-serial-dev

before_install:
    #- sudo apt-get install libhdf5-serial-dev
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda update --yes conda

    # Useful for debugging any issues with conda
    - conda info -a

    #- travis_retry pip install --install-option="--no-cython-compile" Cython==0.22

    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy nose h5py cython matplotlib pandas xlrd Ipython
    - pip install emcee uncertainties codecov lmfit
    #- git clone https://github.com/lmfit/lmfit-py.git
    #- cd lmfit-py
    #- python setup.py install && cd ..

install:
    - python setup.py install

script:
    - cd refnx
    - nosetests

notifications:
    # Perhaps we should have status emails sent to the mailing list, but
    # let's wait to see what people think before turning that on.
    email: false

after_success:
  - codecov
